# Generated by Django 3.0.5 on 2020-05-11 11:34

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerShipping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("primary_address_line", models.CharField(max_length=50)),
                (
                    "secondary_address_line",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("town_or_city", models.CharField(max_length=50)),
                ("county", models.CharField(max_length=50)),
                ("postcode", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=50)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "purchase_date",
                    models.DateField(blank=True, default=datetime.date.today),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
