# Generated by Django 3.0.5 on 2020-05-13 12:44

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_auto_20200511_1234"),
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customershipping",
            name="purchase_date",
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "purchase_date",
                    models.DateField(blank=True, default=datetime.date.today),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.Product",
                    ),
                ),
                (
                    "shipping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="checkout.CustomerShipping",
                    ),
                ),
            ],
        ),
    ]
