# Generated by Django 3.0.5 on 2020-05-21 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_auto_20200511_1234"),
        ("checkout", "0007_auto_20200521_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.Product"
            ),
        ),
    ]
