# Generated by Django 3.0.5 on 2020-05-24 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_auto_20200511_1234"),
        ("checkout", "0008_auto_20200521_2003"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="order_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.Product"
            ),
        ),
    ]
