# Generated by Django 3.0.5 on 2020-05-26 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_auto_20200511_1234"),
        ("checkout", "0014_auto_20200525_2019"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.Product"
            ),
        ),
    ]
