# Generated by Django 3.0.5 on 2020-05-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_auto_20200526_0943"),
        ("checkout", "0016_auto_20200526_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.Product"
            ),
        ),
    ]
