# Generated by Django 3.0.5 on 2020-05-31 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_auto_20200531_1252"),
        ("checkout", "0017_auto_20200528_0925"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customershipping",
            name="postcode",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.Product"
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
