# Generated by Django 3.0.5 on 2020-04-13 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200413_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Awaiting product description.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_available',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(50)]),
            preserve_default=False,
        ),
    ]
