# Generated by Django 3.0.5 on 2020-04-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_auto_20200416_2052"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images"),
        ),
    ]
